### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by theel0ja** [mhart/react-server-example#10]
This message while starting the server, it works but:
> Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by memoryza** [comment]
you can set "react" : "less than version 15" in package.json 。and delete node_modules/react and reinstall or  use  create-react-class

**Comment by mhart** [comment]
Supported in v1.3.0
