### ISSUE TITLE
safeStringify with react 16 hydrate

### ISSUE THREAD

**Issue by againksy** [mhart/react-server-example#13]
safeStringify in react 16 hydrate produces errors like this
`Warning: Text content did not match. Server: "</script>fasdfsfsf </script> " Client: "</script>fasdfsfsf </script>"`

**Comment by mhart** [comment]
Can you show me how to reproduce this?

**Comment by mhart** [comment]
Going to close this due to lack of activity – feel free to reopen if you have a reproduction.
