### ISSUE TITLE
Using server side rendering, componentDidMount didn't get called

### ISSUE THREAD

**Issue by bryanboyan** [mhart/react-server-example#3]
Hi, Michael
Did you verify that componentDidMount did get called when hitting localhost:3000/ ? 
From react document, https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount, it looks like it's not invoked on server side.

I was thinking about how we can integrate with other Js frameworks if we do server side react.

**Comment by mhart** [comment]
`componentDidMount` does not get called on the server, that's correct – in the example here, it enables the button on the page once the DOM has been rendered by the browser (not the server).

**Comment by mhart** [comment]
In terms of other JS frameworks, well that's really up to them :smile_cat: – if they allow server-side rendering (ie, rendering in the absence of any DOM, no `window`, no `document`, etc, etc) – then it should be possible. If not, then you'll just have to do client-side rendering for that portion and attach them in `componentDidMount`.

Going to close this – but feel free to keep asking clarifying questions if you want.

**Comment by bryanboyan** [comment]
Hi, Michael, thanks for answering this, and sorry for replying late.
Then I have a really general question to server-side rendering, since server-side react only renders the relatively static html, and client will render the exact same component to replace them. We do this because of SEO? Imaging the app is really big for server to render, that will cause server load and doesn't help on client load as well?

Thanks

**Comment by mhart** [comment]
@bryanboyan the advantage of React is that it adds checksums to the nodes when you use `renderToString` – and then when you `render` on the client-side, then it checks whether these checksums match what it expects – if they do, then it doesn't need to do anything on the client-side. So the client-side load is very little. This is explained a little here: https://facebook.github.io/react/docs/top-level-api.html#react.rendertostring

**Comment by bryanboyan** [comment]
Michael, that is truly awesome, thanks a lot!
