### ISSUE TITLE
Doesn't work when javascript disabled

### ISSUE THREAD

**Issue by mshahriarinia** [mhart/react-server-example#4]
When you disable javascript in google chrome this example does not work. The whole point of mutual server/client rendering is to get rid of dependency on javascript libraries loading. Any thoughts?

**Comment by mhart** [comment]
When you say "it doesn't work" do you mean that nothing renders? This project is just here to illustrate server-side rendering.

If you're looking for an example of graceful-degradation/progressive-enhancement, this might illustrate that a bit better: https://github.com/mhart/react-server-routing-example

**Comment by mshahriarinia** [comment]
Great! Checking it out now. tnx

Not related to this issue: Do you have any ideas on my question [here](http://stackoverflow.com/questions/30272154/isomorphic-javascript-routes-with-react-route-vs-rest-api-routes). I feel like replicating routes definitions both for client and server (for db access, etc) is inevitable. Any thoughts?
