### ISSUE TITLE
JSON parse error on sanitized HTML comment

### ISSUE THREAD

**Issue by shuhei** [mhart/react-server-example#9]
[This line](https://github.com/mhart/react-server-example/blob/v1.2.6/server.js#L109) causes an JSON parse error because `\!` is not a valid character in JSON.

https://github.com/yahoo/serialize-javascript has [a nice implementation for safely stringifying JSON for HTML](https://github.com/yahoo/serialize-javascript/blob/v1.3.0/index.js#L16-L30).

**Comment by mhart** [comment]
@shuhei you shouldn't be JSON parsing the output of that function – it's used for [assigning to a JavaScript variable](https://github.com/mhart/react-server-example/blob/v1.2.6/server.js#L54)

Are you getting an error on that?

**Comment by shuhei** [comment]
@mhart You are right! Sorry for my oversight...
